
```{r}
library(dplyr)
library(tidyverse)
library(ggplot2)
library(reshape2)
library(ggsci)
```

```{r}
CL_all_metric_tribus <- read.csv("C:\\Users\\Public\\Farkkila_lab_datasets\\Tribus\\Test_case_data\\STELLAR\\output_data\\Tribus_benchmarking\\stellar_cl_benchmarking_stats_report_all.csv")
SB_all_metric_tribus <- read.csv("C:\\Users\\Public\\Farkkila_lab_datasets\\Tribus\\Test_case_data\\STELLAR\\output_data\\Tribus_benchmarking\\stellar_sb_benchmarking_stats_report_all.csv")
CL_all_metric_astir <- read.csv("C:\\Users\\Public\\Farkkila_lab_datasets\\Tribus\\Test_case_data\\STELLAR\\output_data\\Astir_benchmarking\\stellar_cl_benchmarking_stats_report_all.csv")
SB_all_metric_astir <- read.csv("C:\\Users\\Public\\Farkkila_lab_datasets\\Tribus\\Test_case_data\\STELLAR\\output_data\\Astir_benchmarking\\stellar_sb_benchmarking_stats_report_all.csv")
```

```{r}
CL_all_metric_tribus <- CL_all_metric_tribus %>% column_to_rownames(var="X")
colnames(CL_all_metric_tribus) <- c("CL_Tribus")
SB_all_metric_tribus <- SB_all_metric_tribus %>% column_to_rownames(var="X")
colnames(SB_all_metric_tribus) <- c("SB_Tribus")
CL_all_metric_astir <- CL_all_metric_astir %>% column_to_rownames(var="X")
colnames(CL_all_metric_astir) <- c("CL_astir")
SB_all_metric_astir <- SB_all_metric_astir %>% column_to_rownames(var="X")
colnames(SB_all_metric_astir) <- c("SB_astir")
```

```{r}
all_metric_df <- cbind(CL_all_metric_tribus, SB_all_metric_tribus, CL_all_metric_astir, SB_all_metric_astir) %>% rownames_to_column(var="metric")
all_metric_df_melt <- melt(all_metric_df, id=c("metric"))
method <- c(rep("Tribus" , 8) , rep("Astir" , 8))
condition <- c(rep("CL", 4), rep("SB", 4), rep("CL", 4), rep("SB", 4))
all_metric_df_melt <- all_metric_df_melt %>% cbind(method, condition)
```

```{r, fig.width = 14, fig.height=5}
ggplot(all_metric_df_melt, 
        aes(fill=method, y=value, x=interaction(metric, condition))) + 
    geom_bar(position="dodge", stat="identity") + 
    scale_fill_npg()

ggsave(file="all_metric.pdf", width=12, height=4, dpi=300)
```