###################
## QueryStarPlot ##
###################
#' Query a certain cell type
#' 
#' Identify nodes in the tree which resemble a certain profile of "high"
#' or "low" marker expressions.
#'
#' @param fsom    FlowSOM object, as generated by \code{\link{BuildMST}} or
#'        the first list item of \code{\link{FlowSOM}}
#' @param query  Array containing "high" or "low" for the specified column
#'               names of the FlowSOM data
#' @param plot   If true, a plot with a gradient of scores for the nodes is 
#'               shown
#' @param color  Color to use for nodes with a high score in the plot
#' @param debug  If TRUE, some extra output will be printed
#' @param ...    Other parameters to pass to \code{\link{PlotStars}}
#' @return A list, containing the ids of the selected nodes, the individual
#'         scores for all nodes and the scores for each marker for each node
#' @examples
#'    file <- system.file("extdata", "68983.fcs", package="FlowSOM")
#'    # Use the wrapper function to build a flowSOM object (saved in fsom[[1]])
#'    # and a metaclustering (saved in fsom[[2]])
#'    fsom <- FlowSOM(file,compensate = TRUE, transform = TRUE,scale = TRUE,
#'                   colsToUse = c(9,12,14:18), nClus = 10, silent = FALSE,
#'                   xdim=7, ydim=7)
#'    query <- c("PE-Cy7-A" = "high", #CD3
#'               "APC-Cy7-A" = "high", #TCRb
#'               "Pacific Blue-A" = "high") #CD8
#'    query_res <- QueryStarPlot(UpdateNodeSize(fsom[[1]],reset=TRUE), query)
#'    
#'    cellTypes <- factor(rep("Unknown",49),levels=c("Unknown","CD8 T cells"))
#'    cellTypes[query_res$selected] <- "CD8 T cells"
#'    PlotStars(fsom[[1]],
#'                  backgroundValues=cellTypes,
#'                  backgroundColor=c("#FFFFFF00","#ca0020aa"))
#'    
#' @export
QueryStarPlot <- function(fsom, query, plot=TRUE,
                          color="#ca0020",debug=FALSE,...){
  
  scores <- matrix(NA,
                   ncol=length(query),
                   nrow=nrow(fsom$map$medianValues),
                   dimnames=list(NULL,names(query)))
  
  for(marker in names(query)){
    data <- fsom$map$medianValues[,marker]
    if(query[marker]=="high"){
      scores[,marker] = (max(data,na.rm = TRUE) - data)^2
    } else if(query[marker]=="low"){
      scores[,marker] = (data - min(data,na.rm = TRUE))^2
    } else {
      stop("Only high or low marker expressions are 
                supported at the moment")
    }
  }
  
  if(debug){
    message("Scores")
    print(scores)
  }
  
  # Normalize between 0 and 1 and make highest score best
  #scores <- apply(scores,2,function(x){1-((x-min(x,na.rm=TRUE))/
  #                                          (max(x,na.rm=TRUE)-min(x,na.rm=TRUE)))})
  
  # Use 95 percentile instead of the max score
  scores <- apply(scores,2,function(x){1-((x-min(x,na.rm=TRUE))/
                                            (quntile(x, 0.95, na.rm=TRUE)-min(x,na.rm=TRUE)))})
  
  if(debug){
    message("Normalized")
    print(scores)
  }
  
  nodeScores <- apply(scores,1,mean)
  nodeScores[is.na(nodeScores)] <- 0
  if(debug){
    message("nodeScores")
    print(nodeScores)
  }
  
  if(plot){
    PlotStars(fsom, 
              markers = names(query),
              backgroundValues = nodeScores,
              backgroundColor = grDevices::colorRampPalette(
                c("#ffffff00","#ffffff00","#ffffff00",color)),
              query = query,
              ...)
  }
  
  cutoff <- max(nodeScores) *0.95
  
  scores_cutoff <- nodeScores > cutoff
  
  return(list("selected"=which(scores_cutoff),
              "nodeScores"=nodeScores,
              "fullScores"=scores))
}